/** Placeholder recovery UX only: plaintext never leaves memory or reaches storage/network. */
const words = [
  "amber",
  "anchor",
  "apple",
  "april",
  "arch",
  "atom",
  "birch",
  "blue",
  "bridge",
  "cabin",
  "candle",
  "cedar",
  "cloud",
  "coral",
  "dawn",
  "delta",
  "ember",
  "field",
  "flint",
  "forest",
  "harbor",
  "hazel",
  "island",
  "ivory",
  "juniper",
  "kite",
  "lantern",
  "maple",
  "meadow",
  "mercury",
  "moss",
  "north",
  "oasis",
  "olive",
  "orbit",
  "paper",
  "pearl",
  "pine",
  "quiet",
  "raven",
  "river",
  "sable",
  "saffron",
  "shore",
  "silver",
  "solace",
  "stone",
  "summit",
  "thistle",
  "timber",
  "valley",
  "violet",
  "willow",
  "winter",
];
export const recoveryNotice =
  "This versioned recovery ceremony is a placeholder, not a cryptographic key backup.";
export function generateRecoveryPhrase(random: Crypto = crypto) {
  const bytes = new Uint32Array(24);
  random.getRandomValues(bytes);
  return Array.from(bytes, (value) => words[value % words.length]);
}
